/**
 * Authenticated Context Utility for E2E Tests
 * Feature: 062-fix-e2e-auth
 *
 * Provides a consistent way to create authenticated browser contexts
 * using the shared auth state from auth.setup.ts.
 *
 * This utility solves the issue of tests creating browser.newContext()
 * without authentication, causing tests to fail or run unauthenticated.
 *
 * Usage:
 * ```typescript
 * import { createAuthenticatedContext } from '../utils/authenticated-context';
 *
 * test.beforeAll(async ({ browser }) => {
 *   const { context, page } = await createAuthenticatedContext(browser);
 *   // context is authenticated, page is ready to use
 * });
 * ```
 */

import { Browser, BrowserContext, Page } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

// Path to the authenticated storage state (generated by auth.setup.ts)
const AUTH_FILE = 'tests/e2e/fixtures/storage-state-auth.json';
// Path to base storage state (cookie consent only)
const BASE_FILE = 'tests/e2e/fixtures/storage-state.json';

export interface AuthenticatedContextResult {
  context: BrowserContext;
  page: Page;
}

export interface AuthenticatedContextOptions {
  /** Skip using auth state (for testing unauthenticated flows) */
  skipAuth?: boolean;
  /** Additional context options */
  viewport?: { width: number; height: number };
  /** Use base storage state (cookie consent) only */
  baseStateOnly?: boolean;
}

/**
 * Check if the auth state file exists and has valid structure
 */
function isAuthStateFileValid(): boolean {
  try {
    const authPath = path.resolve(AUTH_FILE);
    if (!fs.existsSync(authPath)) {
      console.warn(
        'Auth state file not found. Run auth setup first or tests will log in manually.'
      );
      return false;
    }

    const state = JSON.parse(fs.readFileSync(authPath, 'utf-8'));

    // Check for auth token in localStorage
    const origin = state.origins?.find(
      (o: { origin: string }) =>
        o.origin.includes('localhost:3000') ||
        o.origin.includes('localhost:3001')
    );
    if (!origin?.localStorage) return false;

    const authToken = origin.localStorage.find((item: { name: string }) =>
      item.name.includes('auth-token')
    );

    return !!authToken;
  } catch (error) {
    console.warn('Error checking auth state file:', error);
    return false;
  }
}

/**
 * Create an authenticated browser context using the shared auth state
 *
 * @param browser - Playwright Browser instance
 * @param options - Optional configuration
 * @returns Object with authenticated context and page
 *
 * @example
 * // Basic usage - authenticated context
 * const { context, page } = await createAuthenticatedContext(browser);
 *
 * @example
 * // With custom viewport
 * const { context, page } = await createAuthenticatedContext(browser, {
 *   viewport: { width: 1280, height: 720 }
 * });
 *
 * @example
 * // Unauthenticated context (for testing public pages)
 * const { context, page } = await createAuthenticatedContext(browser, {
 *   skipAuth: true
 * });
 */
export async function createAuthenticatedContext(
  browser: Browser,
  options: AuthenticatedContextOptions = {}
): Promise<AuthenticatedContextResult> {
  const { skipAuth = false, viewport, baseStateOnly = false } = options;

  // Determine which storage state to use
  let storageState: string | { cookies: []; origins: [] } | undefined;

  if (skipAuth) {
    // Empty storage state for unauthenticated tests
    storageState = { cookies: [], origins: [] };
  } else if (baseStateOnly) {
    // Use base state (cookie consent only)
    storageState = fs.existsSync(BASE_FILE) ? BASE_FILE : undefined;
  } else {
    // Use authenticated state if available
    storageState = isAuthStateFileValid() ? AUTH_FILE : undefined;
  }

  // Create context with storage state
  const contextOptions: {
    storageState?: string | { cookies: []; origins: [] };
    viewport?: { width: number; height: number };
  } = {};

  if (storageState) {
    contextOptions.storageState = storageState;
  }

  if (viewport) {
    contextOptions.viewport = viewport;
  }

  const context = await browser.newContext(contextOptions);
  const page = await context.newPage();

  return { context, page };
}

/**
 * Get the path to the auth state file
 * Useful for tests that need to manually specify storage state
 */
export function getAuthStatePath(): string {
  return AUTH_FILE;
}

/**
 * Get the path to the base storage state file (cookie consent only)
 */
export function getBaseStatePath(): string {
  return BASE_FILE;
}

/**
 * Check if auth state is available and valid
 * Tests can use this to decide whether to use shared auth or login manually
 */
export function hasValidAuthState(): boolean {
  return isAuthStateFileValid();
}
